# Generated by Django 5.0.2 on 2024-03-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='время начала')),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='время окончания')),
                ('frequency', models.SmallIntegerField(choices=[(0, 'разово'), (1, 'ежедневно'), (2, 'еженедельно'), (3, 'ежемесячно')], default=0, verbose_name='частота')),
                ('status', models.CharField(choices=[('created', 'создана'), ('started', 'запущена'), ('finished', 'завершена')], default='created', verbose_name='статус')),
                ('recipients', models.ManyToManyField(related_name='mailing', to='mailer.client', verbose_name='получатели')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(verbose_name='время последней попытки')),
                ('status', models.CharField(choices=[('success', 'успешно'), ('error', 'ошибка')], verbose_name='статус')),
                ('response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.mailing')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='тема')),
                ('body', models.TextField(verbose_name='тело')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
    ]
