# Generated by Django 5.0.2 on 2024-04-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('block', 'Can block users')]},
        ),
    ]
